# Generated by Django 3.0.8 on 2020-08-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200803_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link_npa',
            old_name='id_npa',
            new_name='name',
        ),
    ]
