# Generated by Django 3.0.8 on 2020-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200803_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_npa',
            name='id_nda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link_npa',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
    ]
