# Generated by Django 3.0.8 on 2020-08-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200803_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_npa',
            name='id_npa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.npa'),
        ),
    ]
