# Generated by Django 3.0.8 on 2020-08-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200803_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link_npa',
            options={'verbose_name': 'Cсылки', 'verbose_name_plural': 'Cсылки'},
        ),
    ]
